version: '3'
services:
  backend:
    build: ./src    
    ports:
      - "8011:8000"
    environment:
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./src/web-app
    ports:
      - "81:3000"
    volumes:
      - ./src/web-app:/code
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_MapboxAccessToken=${REACT_APP_MapboxAccessToken}
    depends_on:
      - backend
    stdin_open: true
    tty: true    
    command: npm start